use crate::unicode::props::Hst;
use crate::collections::TwoStageTable;

const STAGE_1: [u8; 4352] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 3, 4, 5, 6,
    7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8,
    9, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 8, 9, 3,
    4, 5, 6, 7, 8, 9, 3, 10, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

const STAGE_2: &[&[Hst]] = &[
    &[
        // Block 0
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
    ],
    &[
        // Block 1
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
    ],
    &[
        // Block 2
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::L,
        Hst::L, Hst::L, Hst::L, Hst::L, Hst::L, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
    ],
    &[
        // Block 3
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
    ],
    &[
        // Block 4
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
    ],
    &[
        // Block 5
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
    ],
    &[
        // Block 6
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
    ],
    &[
        // Block 7
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
    ],
    &[
        // Block 8
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
    ],
    &[
        // Block 9
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
    ],
    &[
        // Block 10
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LV, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT,
        Hst::LVT, Hst::LVT, Hst::LVT, Hst::LVT, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V,
        Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::V, Hst::NA,
        Hst::NA, Hst::NA, Hst::NA, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T, Hst::T,
        Hst::T, Hst::T, Hst::T, Hst::T, Hst::NA, Hst::NA, Hst::NA, Hst::NA,
    ],
];

pub(crate) fn hst(cp: u32) -> Hst {
    let tst: TwoStageTable<Hst, u8> = TwoStageTable::new(&STAGE_1, STAGE_2, 256);
    tst.at(cp)
}
